### ISSUE TITLE
please consider getting rid of indirect notation

### ISSUE THREAD

**Issue by wchristian** [ReneNyffenegger/PerlModules#1] opened 2017-02-10 20:54 UTC
As mentioned here, with a link as to why it's dangerous: https://www.reddit.com/r/perl/comments/5t6vfw/github_renenyffeneggerperlmodules_very_simple/ddkuja3/

**Comment by ReneNyffenegger** [comment] 2017-02-14 09:25
I heve merged Kivanc's PR and believe the issue is now closed.

**Closed as completed by ReneNyffenegger** 2017-02-14 09:25 UTC
